# Generated by Django 3.1.1 on 2020-10-09 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Publishing_HouseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'publishing_house',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_link', models.URLField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField(default=None, null=True)),
                ('description', models.CharField(max_length=500)),
                ('publish_year', models.DateField()),
                ('count', models.IntegerField(blank=True, default=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ManyToManyField(to='author.AuthorModel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.categorymodel')),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.publishing_housemodel')),
            ],
            options={
                'db_table': 'books',
                'ordering': ('-created',),
            },
        ),
    ]
